export default [
  {
    ignores: [
      ".next*/**",
      ".next.bak-*/**",
      ".local/**",
      ".npm-cache/**",
      ".superpowers/**",
      ".cleanup-quarantine/**",
      ".agents/**",
      ".claude/**",
      ".codex/**",
      ".github/agents/**",
      ".github/hooks/**",
      ".github/scripts/**",
      ".github/skills/**",
      ".tmp/**",
      "scratch/**",
      "scripts/_attic/**",
      "playwright-report/**",
      "test-results/**",
      "node_modules/**",
    ],
  },
];
