[build]
builder = "DOCKERFILE"

[deploy]
releaseCommand = "node scripts/release.cjs"
startCommand = "npm run start:prod"
healthcheckPath = "/api/health"
healthcheckTimeout = 30
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3
