/**
 * activityUniversePayload.ts — v2.7 Phase 38 (SCALE-02).
 *
 * Server-shared ownership of the activity-universe binary payload artifact:
 * canonical paths, meta reader, and the pure meta assembler shared by the
 * builder script and the /api/activity-universe/payload route. The artifact
 * pair lives under gitignored .embedding/ and is (re)generated by
 * scripts/build-activity-universe-payload.ts after each pipeline run.
 */
import { existsSync, readFileSync } from "node:fs";
import { join } from "node:path";

export const ACTIVITY_UNIVERSE_BIN = ".embedding/activity-universe.bin";
export const ACTIVITY_UNIVERSE_META = ".embedding/activity-universe-meta.json";

export interface ActivityUniverseCoverage {
  measuredAt: string;
  total: number;
  nullEmail: number;
  matchedPair: number;
  matchedEmailOnly: number;
  unmatchedEmail: number;
  resolvedPairRate: number;
  resolvedEmailRate: number;
  unknownAuthorRate: number;
}

/** Row-index → id anchor spacing: every ANCHOR_STRIDE-th id is recorded in meta. */
export const ID_ANCHOR_STRIDE = 10_000;

export interface ActivityUniverseMeta {
  version: 1;
  embeddingRunId: string;
  generatedAt: string;
  count: number;
  /** Code-indexed label lists + month floor/count from the pipeline dicts. */
  dicts: Record<string, unknown>;
  /** ACT-02 honest author-coverage figures (38-01 measurement). */
  coverage: ActivityUniverseCoverage;
  /**
   * Phase 39 (ACT-04): ids of rows 0, 10000, 20000, … in the artifact's
   * ORDER BY id stream. Row index → id resolution = anchor + ≤10k OFFSET on
   * the PK index. Anchors MUST come from the build (not runtime) so they stay
   * consistent with the payload ordering even if the table drifts afterwards.
   * Optional: absent on pre-39 artifacts (eventDetail then reports stale).
   */
  idAnchors?: string[];
}

/** Pure meta assembly — the single shape the route serves and Phase 39 consumes. */
export function assembleActivityUniverseMeta(args: {
  embeddingRunId: string;
  generatedAt: string;
  count: number;
  dicts: Record<string, unknown>;
  coverage: ActivityUniverseCoverage;
  idAnchors?: string[];
}): ActivityUniverseMeta {
  return { version: 1, ...args };
}

/**
 * Anchor lookup for a row index: returns the anchor id and the remaining
 * offset within the anchor's stride window, or null when the index is out of
 * range for the recorded anchors.
 */
export function anchorFor(
  idAnchors: readonly string[],
  index: number,
): { anchorId: string; offset: number } | null {
  if (!Number.isInteger(index) || index < 0) return null;
  const slot = Math.floor(index / ID_ANCHOR_STRIDE);
  if (slot >= idAnchors.length) return null;
  return { anchorId: idAnchors[slot], offset: index % ID_ANCHOR_STRIDE };
}

export function activityUniversePaths(cwd = process.cwd()): { bin: string; meta: string } {
  return { bin: join(cwd, ACTIVITY_UNIVERSE_BIN), meta: join(cwd, ACTIVITY_UNIVERSE_META) };
}

/** Parsed meta, or null when the artifact pair is absent (honest 404 upstream). */
export function readActivityUniverseMeta(cwd = process.cwd()): ActivityUniverseMeta | null {
  const { bin, meta } = activityUniversePaths(cwd);
  if (!existsSync(bin) || !existsSync(meta)) return null;
  try {
    return JSON.parse(readFileSync(meta, "utf8")) as ActivityUniverseMeta;
  } catch {
    return null;
  }
}
