/**
 * activityUniversePayload.ts — v2.7 Phase 38 (SCALE-02).
 *
 * Server-shared ownership of the activity-universe binary payload artifact:
 * canonical paths, meta reader, and the pure meta assembler shared by the
 * builder script and the /api/activity-universe/payload route. The artifact
 * pair lives under gitignored .embedding/ and is (re)generated by
 * scripts/build-activity-universe-payload.ts after each pipeline run.
 */
import { existsSync, readFileSync } from "node:fs";
import { join } from "node:path";

export const ACTIVITY_UNIVERSE_BIN = ".embedding/activity-universe.bin";
export const ACTIVITY_UNIVERSE_META = ".embedding/activity-universe-meta.json";

export interface ActivityUniverseCoverage {
  measuredAt: string;
  total: number;
  nullEmail: number;
  matchedPair: number;
  matchedEmailOnly: number;
  unmatchedEmail: number;
  resolvedPairRate: number;
  resolvedEmailRate: number;
  unknownAuthorRate: number;
}

export interface ActivityUniverseMeta {
  version: 1;
  embeddingRunId: string;
  generatedAt: string;
  count: number;
  /** Code-indexed label lists + month floor/count from the pipeline dicts. */
  dicts: Record<string, unknown>;
  /** ACT-02 honest author-coverage figures (38-01 measurement). */
  coverage: ActivityUniverseCoverage;
}

/** Pure meta assembly — the single shape the route serves and Phase 39 consumes. */
export function assembleActivityUniverseMeta(args: {
  embeddingRunId: string;
  generatedAt: string;
  count: number;
  dicts: Record<string, unknown>;
  coverage: ActivityUniverseCoverage;
}): ActivityUniverseMeta {
  return { version: 1, ...args };
}

export function activityUniversePaths(cwd = process.cwd()): { bin: string; meta: string } {
  return { bin: join(cwd, ACTIVITY_UNIVERSE_BIN), meta: join(cwd, ACTIVITY_UNIVERSE_META) };
}

/** Parsed meta, or null when the artifact pair is absent (honest 404 upstream). */
export function readActivityUniverseMeta(cwd = process.cwd()): ActivityUniverseMeta | null {
  const { bin, meta } = activityUniversePaths(cwd);
  if (!existsSync(bin) || !existsSync(meta)) return null;
  try {
    return JSON.parse(readFileSync(meta, "utf8")) as ActivityUniverseMeta;
  } catch {
    return null;
  }
}
