// ── Revit BIM Family Categories ──
// Extracted from input.csv — 114 unique categories, no OST codes, no duplicates

export const CATEGORY_GROUPS = {
  Structural: [
    "Columns",
    "Structural Columns",
    "Structural Connections",
    "Structural Fabric Areas",
    "Structural Fabric Reinforcement",
    "Structural Foundations",
    "Structural Framing",
    "Structural Path Reinforcement",
    "Structural Rebar",
    "Structural Rebar Couplers",
    "Structural Stiffeners",
    "Structural Tendons",
    "Structural Trusses",
    "Structural Area Reinforcement",
    "Expansion Joints",
  ],
  Architectural: [
    "Casework",
    "Ceilings",
    "Curtain Panels",
    "Curtain Systems",
    "Curtain Wall Mullions",
    "Doors",
    "Floors",
    "Ramps",
    "Roofs",
    "Roofs - Gutters",
    "Stairs",
    "Stairs - Landings",
    "Stairs - Runs",
    "Stairs - Supports",
    "Stairs - Treads/Risers",
    "Walls",
    "Windows",
    "Railings",
    "Railings - Balusters",
    "Railings - Handrails",
    "Railings - Supports",
    "Railings - Terminations",
    "Railings - Top Rails",
    "Signage",
  ],
  "MEP — Mechanical": [
    "Air Terminals",
    "Duct Accessories",
    "Duct Fittings",
    "Duct Insulations",
    "Duct Linings",
    "Duct Placeholders",
    "Ducts",
    "Flex Ducts",
    "Mechanical Control Devices",
    "Mechanical Equipment",
    "MEP Ancillary Framing",
    "MEP Fabrication Containment",
    "MEP Fabrication Ductwork",
    "MEP Fabrication Ductwork Stiffeners",
    "MEP Fabrication Hangers",
    "MEP Fabrication Pipework",
  ],
  "MEP — Electrical": [
    "Cable Tray Fittings",
    "Cable Trays",
    "Communication Devices",
    "Conduit",
    "Conduit Fittings",
    "Data Devices",
    "Electrical Equipment",
    "Electrical Fixtures",
    "Fire Alarm Devices",
    "Lighting Devices",
    "Lighting Fixtures",
    "Nurse Call Devices",
    "Security Devices",
    "Telephone Devices",
    "Wire",
    "Audio Visual Devices",
  ],
  "MEP — Plumbing & Fire": [
    "Fire Protection",
    "Flex Pipes",
    "Pipe Accessories",
    "Pipe Fittings",
    "Pipe Insulations",
    "Pipe Placeholders",
    "Pipes",
    "Piping Systems",
    "Plumbing Equipment",
    "Plumbing Fixtures",
    "Sprinklers",
  ],
  "Site & Infrastructure": [
    "Abutments",
    "Bearings",
    "Bridge Cables",
    "Bridge Decks",
    "Bridge Framing",
    "Hardscape",
    "Parking",
    "Piers",
    "Planting",
    "Roads",
    "Site",
    "Topography",
    "Toposolid",
    "Vertical Circulation",
  ],
  "Furniture & Equipment": [
    "Entourage",
    "Food Service Equipment",
    "Furniture",
    "Furniture Systems",
    "Medical Equipment",
    "Specialty Equipment",
  ],
  Other: [
    "Detail Items",
    "Generic Models",
    "Grids",
    "Levels",
    "Lines",
    "Mass",
    "RVT Links",
    "Raster Images",
    "Scope Boxes",
    "Section Boxes",
    "Temporary Structures",
    "Vibration Management",
  ],
} as const;

// Group names
export type CategoryGroup = keyof typeof CATEGORY_GROUPS;

export const CATEGORY_GROUP_NAMES = Object.keys(CATEGORY_GROUPS) as CategoryGroup[];
