ALTER TABLE "AccGraphLayoutCache"
ADD COLUMN "nodes" JSONB NOT NULL DEFAULT '[]'::jsonb,
ADD COLUMN "edges" JSONB NOT NULL DEFAULT '[]'::jsonb,
ADD COLUMN "edgeCount" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN "instanceCount" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN "projectCount" INTEGER NOT NULL DEFAULT 0;
